[package]
name = "ble-midi"
version = "0.1.0"
edition = "2021"

[dependencies]
ble-peripheral-rust = "0.2.0"
coremidi = "0.8.0"
log = "0.4.25"
pretty_env_logger = "0.5.0"
tokio = "1.43.0"
uuid = "1.12.1"
